// Get Cities list
export const GET_CITIES_LIST_REQUEST = 'GET_CITIES_LIST_REQUEST';
export const GET_CITIES_LIST_SUCCESS = 'GET_CITIES_LIST_SUCCESS';
export const GET_CITIES_LIST_FAIL = 'GET_CITIES_LIST_FAIL';